---
- name: Play that has outer and inner loop
  hosts: localhost
  tasks: 
    - include_tasks: tasks/loop_task.yml
      loop: 
        - sujan
        - joe
        - james
      loop_control:
        loop_var: other_info
